language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x ./scripts/cibuild
script: "./scripts/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_bc98c29f2d04_key -iv $encrypted_bc98c29f2d04_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d

addons:
  ssh_known_hosts: henziger.se

before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/_site/ travis@henziger.se:/var/www/landing-page
  on:
    branch: master
