# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://henziger.se
title: henziger.se
email: eric@henziger.se
author: Eric Henziger
description: Eric Henziger's landing page.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/henziger
  - title: github
    url: https://github.com/henziger
  - title: linkedin
    url: https://se.linkedin.com/in/erichenziger
