# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://henziger.se
title: Eric Henziger
email: eric@henziger.se
author: Eric Henziger
description:
 sv: Eric Henzigers startsida.
 en: Eric Henziger's landing page.
copyright: 'Copyright &copy; 2017 Eric Henziger. All Rights Reserved.'

# ----------------------- #
# Translations & Language #
# ----------------------- #
t:
  sv:
    home: "Hem"
    proj: "Projekt"
    contact: "Kontakt"
    about: "Om henziger.se"
    keep_in_touch: "Kontakta mig"
  en:
    home: "Home"
    proj: "Projects"
    contact: "Contact"
    about: "About"
    keep_in_touch: "Keep in touch"

index:
  sv:
  en: en.html

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/henziger
  - title: github
    url: https://github.com/henziger
  - title: linkedin
    url: https://se.linkedin.com/in/erichenziger
  - title: wordpress
    url: http://henziger.com
    descr:
      sv: Blogg
      en: Blog
  - title: facebook
    url: https://www.facebook.com/eric.henziger
  - title: instagram
    url: https://www.instagram.com/mjauvoff/
  - title: envelope
    url: mailto:eric@henziger.se
    descr:
      sv: E-post
      en: Email me